version: '3.8'
services:
  postgresdb:
    image: postgres:14.1-alpine
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./projects/db/data:/var/lib/postgresql/data
      - ./projects/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    image: api
    container_name: api
    build: ./app/projects/api
    depends_on:
      - postgresdb
    ports:
      - 5000:5000
    environment:
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=1
      - DB_NAME=user
    links:
      - postgresdb
    volumes:
      - ./app:/app
volumes:
  postgresdb:
    driver: local
